[env:esp32dev]
platform   = espressif32
board      = esp32dev
framework  = arduino

lib_deps =
  bblanchon/ArduinoJson@^7.0.0
  knolleary/PubSubClient@^2.8
  milesburton/DallasTemperature@^3.11.0
  paulstoffregen/OneWire@^2.3.8

build_flags =
  -DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
  -DWIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"
  -DTB_HOST=\"${sysenv.TB_HOST}\"
  -DTB_HTTP_PORT=${sysenv.TB_HTTP_PORT}
  -DTB_ACCESS_TOKEN=\"${sysenv.TB_ACCESS_TOKEN}\"

monitor_speed = 115200
